language: bash
dist: bionic

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_ENABLE_SILENT_REPORT: y
    - PATH: /snap/bin:$PATH

addons:
  snaps:
    - name: snapcraft
      channel: stable
      classic: true
    - name: http
    - name: lxd
      channel: stable

install:
  - sudo apt autoremove --yes --purge lxd lxd-client
  - sudo /snap/bin/lxd init --auto
  - sudo /snap/bin/lxd waitready
script:
  # Workaround until https://github.com/snapcore/snapcraft/pull/3240 is released.
  - sudo bash -c "unset SUDO_USER && snapcraft --use-lxd"
after_failure:
  - http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16
