name: ffmpeg
adopt-info: ffmpeg
summary: A complete solution to record, convert and stream audio and video.
description: |
 FFmpeg is the leading multimedia framework, able to decode, encode,
 transcode, mux, demux, stream, filter and play pretty much anything that
 humans and machines have created. It supports the most obscure ancient formats
 up to the cutting edge. No matter if they were designed by some standards
 committee, the community or a corporation.

grade: stable
confinement: strict

parts:
#### nv-codec-headers
#
  nv-codec-headers:
    plugin: make
    source: https://github.com/FFmpeg/nv-codec-headers/releases/download/n8.2.15.4/nv-codec-headers-8.2.15.4.tar.gz
    override-build: |
      make install PREFIX=/usr
    build-packages:
      - pkg-config
#
####

#### x264
#
  nasm:
    plugin: autotools
    source: https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.xz
    configflags:
      - --prefix=/usr

  x264:
    plugin: autotools
    source: http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20181030-2245-stable.tar.bz2
    configflags:
      - --prefix=/usr
      - --disable-cli
      - --enable-shared
      - --enable-strip
    prime:
      - usr/lib
      - -usr/lib/pkgconfig
    build-packages:
      - libva-dev
    after:
      - nasm
#
####


#### x265
#
  x265:
    plugin: nil
    source: https://bitbucket.org/multicoreware/x265/downloads/x265_2.7.tar.gz
    build-packages:
      - cmake
      - yasm
      - on amd64: [ libnuma-dev ]
      - on i386:  [ libnuma-dev ]
      - on arm64: [ libnuma-dev ]
    stage-packages:
      - on amd64: [ libnuma1 ]
      - on i386:  [ libnuma1 ]
      - on arm64: [ libnuma1 ]
    override-build: |
      cd source
      cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/usr"
      make
      make install
    prime:
      - usr/lib
#
####


#### fdk-aac
#
  fdk-aac:
    plugin: autotools
    source: https://github.com/mstorsjo/fdk-aac/archive/v0.1.6.tar.gz
    build-packages:
      - g++
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - usr/lib
      - -usr/lib/pkgconfig
#
####


#### lame
#
  lame:
    plugin: autotools
    source: http://downloads.sourceforge.net/lame/lame-3.100.tar.gz
    configflags:
      - --prefix=/usr
      - --disable-static
      - --enable-nasm
    prime:
      - usr/lib
      - -usr/lib/pkgconfig
    after:
      - nasm
#
####


#### twolame
#
  twolame:
    plugin: autotools
    source: http://downloads.sourceforge.net/twolame/twolame-0.3.13.tar.gz
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - usr/lib
      - -usr/lib/pkgconfig
    after:
      - libsndfile
#
####


#### opus
#
  opus:
    plugin: autotools
    source: https://ftp.osuosl.org/pub/xiph/releases/opus/opus-1.2.1.tar.gz
    configflags:
      - --prefix=/usr
      - --disable-doc
      - --disable-extra-programs
      - --disable-static
    prime:
      - usr/lib
      - -usr/lib/pkgconfig
#
####


#### libvpx
#
  libogg:
    plugin: autotools
    source: https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.3.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share

  libvorbis:
    plugin: autotools
    source: https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.6.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share
    after:
      - libogg

  libvpx:
    plugin: autotools
    source: https://github.com/webmproject/libvpx/archive/v1.7.0.tar.gz
    build-packages:
      - yasm
    configflags:
      - --prefix=/usr
      - --enable-shared
      - --enable-postproc
      - --enable-runtime-cpu-detect
      - --enable-vp8
      - --enable-vp9
      - --enable-vp9-highbitdepth
      - --enable-vp9-postproc
      - --disable-examples
      - --disable-debug-libs
      - --disable-debug
      - --disable-static
      - --disable-unit-tests
      - --as=yasm
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
    after:
      - libvorbis
#
####


#### libtheora
#
  libtheora:
    plugin: autotools
    source: https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
    configflags:
      - --prefix=/usr
      - --enable-shared
      - --disable-examples
    override-build: |
      # Patch libtheora so it compile with libpng16
      sed -i 's/png_sizeof/sizeof/g' examples/png2theora.c
      snapcraftctl build
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/doc
    after:
      - libvorbis
      - libpng
#
####

#### v4l-utils
#
  v4l-utils:
    plugin: autotools
    source: https://linuxtv.org/downloads/v4l-utils/v4l-utils-1.14.2.tar.bz2
    configflags:
      - --prefix=/usr
      - --enable-shared
      - --enable-libv4l
      - --disable-libdvbv5
      - --disable-qv4l2
      - --disable-v4l-utils
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/sbin
      - -usr/share/doc
      - -usr/share/man
    after:
      - alsa-lib
#
####


#### libpng
#
  zlib:
    plugin: autotools
    source: https://zlib.net/zlib-1.2.11.tar.gz
    configflags:
      - --prefix=/usr
    prime:
      - -usr/include
      - -usr/lib/libz.a
      - -usr/lib/pkgconfig
      - -usr/share/doc
      - -usr/share/man

  libpng:
    plugin: autotools
    source: http://ftp-osl.osuosl.org/pub/libpng/src/libpng16/libpng-1.6.34.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/doc
      - -usr/share/man
    after:
      - zlib
#
####


#### libass
#
  fribidi:
    plugin: autotools
    source: https://github.com/fribidi/fribidi/releases/download/v1.0.2/fribidi-1.0.2.tar.bz2
    configflags:
      - --prefix=/usr
      - --disable-docs
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig

  libass:
    plugin: autotools
    source: https://github.com/libass/libass/releases/download/0.14.0/libass-0.14.0.tar.xz
    build-packages:
      - libfontconfig1-dev
      - libfreetype6-dev
    stage-packages:
      - libfontconfig1
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
    after:
      - libpng
      - fribidi
      - nasm
#
####


#### pulseaudio
#
  json-c:
    plugin: autotools
    source: https://github.com/json-c/json-c/archive/json-c-0.13-20171207.tar.gz
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - -usr/include
      - -usr/lib/pkgconfig

  alsa-lib:
    plugin: autotools
    source: https://ftp.osuosl.org/pub/blfs/conglomeration/alsa-lib/alsa-lib-1.1.6.tar.bz2
    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
      - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
      - --disable-static
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/alsa/alsa.conf
      - -usr/share/alsa/pcm
      - -usr/share/alsa/topology/broadwell

  flac:
    plugin: autotools
    source: https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.2.tar.xz
    build-packages:
      - libtool
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share
    after:
      - libogg
      - libvorbis
      - nasm

  libsndfile:
    plugin: autotools
    source: https://github.com/erikd/libsndfile/archive/1.0.28.tar.gz
    build-packages:
      - autogen
      - pkg-config
      - python
    configflags:
      - --prefix=/usr
      - --disable-sqlite
      - --disable-static
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/doc
      - -usr/share/man
    after:
      - alsa-lib
      - flac
      - libvorbis

  pulseaudio:
    plugin: autotools
    source: https://github.com/pulseaudio/pulseaudio.git
    source-tag: v12.2
    override-build: |
      NOCONFIGURE=1 ./bootstrap.sh
      snapcraftctl build
    build-packages:
      - intltool
      - libasyncns-dev
      - libcap-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libltdl-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libudev-dev
      - pkg-config
    stage-packages:
      - libasyncns0
      - libcap2
      - libdbus-1-3
      - libglib2.0-0
      - libltdl7
      - libspeex1
      - libspeexdsp1
      - libudev1
    configflags:
      - --prefix=/usr
      - --disable-atomic-arm-linux-helpers
      - --disable-bluez4
      - --disable-bluez5
      - --disable-default-build-tests
      - --disable-esound
      - --disable-gconf
      - --disable-gtk3
      - --disable-hal-compat
      - --disable-rpath
      - --disable-samplerate
      - --disable-static
      - --disable-tests
      - --disable-x11
    stage:
      - usr/include
      - usr/lib
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/bash-completion
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/vala
      - -usr/share/zsh
    after:
      - json-c
      - libsndfile
#
####

  ffmpeg:
    plugin: autotools
    source: https://github.com/FFmpeg/FFmpeg.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag -l | grep -v v | sort -rV | head -n1)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/n//')"
      last_released_tag="$(snap info ffmpeg | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$last_committed_tag_ver"
    build-packages:
      - libbz2-dev
      - libdrm-dev
      - liblzma-dev
      - libomxil-bellagio-dev
      - libsctp-dev
      - libvdpau-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxv-dev
      - nvidia-cuda-dev
      - pkg-config
      - yasm
      - on amd64: [ libcrystalhd-dev ]
      - on i386:  [ libcrystalhd-dev ]
    stage-packages:
      - i965-va-driver
      - libdrm2
      - libva-drm1
      - libvdpau-va-gl1
      - libx11-6
      - libxau6
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxv1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - on amd64: [ libcrystalhd3 ]
      - on i386:  [ libcrystalhd3 ]
    configflags:
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-avisynth
      - --enable-cuda
      - --enable-cuvid
      - --enable-libdrm
      - --enable-ffplay
      - --enable-gpl
      - --enable-libass
      - --enable-libfdk-aac
      - --enable-libfontconfig
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libnpp
      - --enable-libopus
      #- --enable-libpulse
      - --enable-libspeex
      - --enable-libtheora
      - --enable-libtwolame
      - --enable-libv4l2
      - --enable-libvorbis
      - --enable-libx264
      - --enable-libx265
      - --enable-libxcb
      - --enable-nonfree
      - --enable-nvenc
      - --enable-omx
      - --enable-runtime-cpudetect
      - --enable-shared
      - --enable-vaapi
      - --enable-vdpau
      - --enable-version3
      - --enable-xlib
    after:
      - nv-codec-headers
      - x264
      - x265
      - fdk-aac
      - lame
      - twolame
      - opus
      - libvpx
      - libtheora
      - v4l-utils
      - libass
      - pulseaudio
    prime:
      - usr/bin
      - usr/lib
      - -usr/lib/pkgconfig
      - -usr/include
      - -usr/share/doc
      - -usr/share/man

  ffmpeg-wrapper:
    plugin: dump
    source: files
    stage-packages:
      - mesa-utils
    organize:
      'ffplay': bin/
      'ffmpeg': bin/
      'ffprobe': bin/
      'wrapper': bin/
    after:
      - ffmpeg

apps:
  ffmpeg:
    command: bin/ffmpeg
    environment:
      # Tell libGL where to find the drivers
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_PLATFORM/dri
      # Mesa Libs for OpenGL support
      # Workaround in snapd for proprietary nVidia drivers mounts the drivers in
      # /var/lib/snapd/lib/gl that needs to be in LD_LIBRARY_PATH
      # Without that OpenGL using apps do not work with the nVidia drivers.
      # Ref.: https://bugs.launchpad.net/snappy/+bug/1588192
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_PLATFORM/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_PLATFORM/mesa-egl:$LIBGL_DRIVERS_PATH:/var/lib/snapd/lib/gl
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - wayland
      - x11
  ffprobe:
    command: bin/ffprobe
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - wayland
      - x11
  ffplay:
    command: bin/ffplay
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - wayland
      - x11
