name: ffmpeg
adopt-info: ffmpeg
summary: A complete solution to record, convert and stream audio and video.
description: |
 FFmpeg is the leading multimedia framework, able to decode, encode,
 transcode, mux, demux, stream, filter and play pretty much anything that
 humans and machines have created. It supports the most obscure ancient formats
 up to the cutting edge. No matter if they were designed by some standards
 committee, the community or a corporation.

grade: stable
confinement: strict

parts:
  nv-codec-headers:
    plugin: make
    source: https://github.com/FFmpeg/nv-codec-headers/releases/download/n8.2.15.4/nv-codec-headers-8.2.15.4.tar.gz
    override-build: |
      make install PREFIX=/usr
    build-packages:
      - pkg-config

  nasm:
    plugin: autotools
    source: https://www.nasm.us/pub/nasm/releasebuilds/2.14/nasm-2.14.tar.gz
    configflags:
      - --prefix=/usr
    prime:
      - -*

  x264:
    plugin: autotools
    source: http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20181030-2245-stable.tar.bz2
    configflags:
      - --prefix=/usr
      - --disable-cli
      - --enable-shared
      - --enable-strip
    prime:
      - usr/lib
      - -usr/lib/pkgconfig
    build-packages:
      - libva-dev
    after:
      - nasm

  x265:
    plugin: nil
    source: https://bitbucket.org/multicoreware/x265/downloads/x265_2.7.tar.gz
    build-packages:
      - cmake
      - yasm
      - on amd64: [ libnuma-dev ]
      - on i386:  [ libnuma-dev ]
      - on arm64: [ libnuma-dev ]
    stage-packages:
      - on amd64: [ libnuma1 ]
      - on i386:  [ libnuma1 ]
      - on arm64: [ libnuma1 ]
    override-build: |
      cd source
      cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/usr"
      make
      make install
    prime:
      - usr/lib

  fdk-aac:
    plugin: autotools
    source: https://github.com/mstorsjo/fdk-aac/archive/v0.1.6.tar.gz
    build-packages:
      - g++
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - usr/lib
      - -usr/lib/pkgconfig

  libvpx:
    plugin: autotools
    source: https://github.com/webmproject/libvpx/archive/v1.7.0.tar.gz
    build-packages:
      - yasm
    build-packages:
      - libvorbis-dev
    stage-packages:
      - libvorbis0a
      - libvorbisenc2
    configflags:
      - --prefix=/usr
      - --enable-shared
      - --enable-postproc
      - --enable-runtime-cpu-detect
      - --enable-vp8
      - --enable-vp9
      - --enable-vp9-highbitdepth
      - --enable-vp9-postproc
      - --disable-examples
      - --disable-debug-libs
      - --disable-debug
      - --disable-static
      - --disable-unit-tests
      - --as=yasm
    prime:
      - usr/lib
      - -usr/include
      - -usr/lib/pkgconfig


  ffmpeg:
    plugin: autotools
    source: https://github.com/FFmpeg/FFmpeg.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag -l | grep -v v | sort -rV | head -n1)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/n//')"
      last_released_tag="$(snap info ffmpeg | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$last_committed_tag_ver"
    build-packages:
      - libass-dev
      - libbz2-dev
      - libdrm-dev
      - liblzma-dev
      - libmp3lame-dev
      - libomxil-bellagio-dev
      - libopenal-dev
      - libopus-dev
      - libpulse-dev
      - libsctp-dev
      - libspeex-dev
      - libtheora-dev
      - libtwolame-dev
      - libv4l-dev
      - libvdpau-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxv-dev
      - ocl-icd-opencl-dev
      - opencl-headers      
      - pkg-config
      - yasm
      - on amd64: [ libcrystalhd-dev ]
      - on i386:  [ libcrystalhd-dev ]
    stage-packages:
      - i965-va-driver
      - libass5
      - libdrm2
      - libmp3lame0
      - libopenal1
      - libopus0
      - libpulse0
      - libspeex1
      - libtheora0
      - libtwolame0
      - libv4l-0
      - libv4l2rds0
      - libva-drm1
      - libvdpau-va-gl1
      - libx11-6
      - libxau6
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxv1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - ocl-icd-libopencl1
      - on amd64: [ libcrystalhd3 ]
      - on i386:  [ libcrystalhd3 ]
    configflags:
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-avisynth
      - --enable-cuda
      - --enable-cuvid
      - --enable-libdrm
      - --enable-ffplay
      - --enable-gpl
      - --enable-libass
      - --enable-libfdk-aac
      - --enable-libfontconfig
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libopus
      - --enable-libpulse
      - --enable-libspeex
      - --enable-libtheora
      - --enable-libtwolame
      - --enable-libv4l2
      - --enable-libvorbis
      - --enable-libvpx
      - --enable-libx264
      - --enable-libx265
      - --enable-libxcb
      - --enable-nonfree
      - --enable-nvenc
      - --enable-omx
      - --enable-openal
      - --enable-opencl
      - --enable-runtime-cpudetect
      - --enable-shared
      - --enable-vaapi
      - --enable-vdpau
      - --enable-version3
      - --enable-xlib
    after:
      - nv-codec-headers
      - x264
      - x265
      - fdk-aac
      - libvpx
    prime:
      - usr/bin
      - usr/lib
      - -usr/lib/pkgconfig
      - -usr/include
      - -usr/share/doc
      - -usr/share/man

  ffmpeg-wrapper:
    plugin: dump
    source: files
    stage-packages:
      - mesa-utils
    organize:
      'ffplay': bin/
      'ffmpeg': bin/
      'ffprobe': bin/
      'wrapper': bin/
    after:
      - ffmpeg

apps:
  ffmpeg:
    command: bin/ffmpeg
    environment:
      # Tell libGL where to find the drivers
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_PLATFORM/dri
      # Mesa Libs for OpenGL support
      # Workaround in snapd for proprietary nVidia drivers mounts the drivers in
      # /var/lib/snapd/lib/gl that needs to be in LD_LIBRARY_PATH
      # Without that OpenGL using apps do not work with the nVidia drivers.
      # Ref.: https://bugs.launchpad.net/snappy/+bug/1588192
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_PLATFORM/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_PLATFORM/mesa-egl:$LIBGL_DRIVERS_PATH:/var/lib/snapd/lib/gl
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - wayland
      - x11
  ffprobe:
    command: bin/ffprobe
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - wayland
      - x11
  ffplay:
    command: bin/ffplay
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - wayland
      - x11